name: turbo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  intl: ^0.19.0
  flutter_localization: ^0.2.0

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5

  # Dependency Injection
  get_it: ^7.7.0

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1

  # Data Persistence
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2

  # UI
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  dots_indicator: ^3.0.0
  another_flushbar: ^1.12.30

  # Code Generation
  freezed_annotation: ^2.4.1

  # Functional Programming
  dartz: ^0.10.1

  # Reactive Programming
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/SFPro/
    - lang/
    - assets/images/
    - assets/images/icons/nav_bar_icons/
    - .env

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SFPro-Medium.OTF
        - asset: assets/fonts/SFPro/SFPro-Regular.OTF
        - asset: assets/fonts/SFPro/SFPro-Italic.OTF
          style: italic
        - asset: assets/fonts/SFPro/SFPro-Bold.OTF
          weight: 700


flutter_native_splash:
  color: "#EEE9E9"
  image: assets/images/logo.png
  android: true
  ios: true
  color_dark: "#EEE9E9"

android_12:
  image: assets/images/logo.png
  icon_background_color: "#EEE9E9"
  image_dark: assets/images/logo.png
  icon_background_color_dark: "#EEE9E9"