name: turbo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any

  another_flushbar: ^1.12.30
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  flutter_svg: ^2.0.10+1

  dio: ^5.4.3+1
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1

  flutter_dotenv: ^5.1.0

  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3
  flutter_localization: ^0.2.0
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.5
  flutter_secure_storage: ^9.2.2
  dots_indicator: ^3.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  freezed: ^2.5.2
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/SFPro/
    - lang/
    - assets/images/
    - assets/images/icons/nav_bar_icons/
    - .env

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SFPro-Medium.OTF
        - asset: assets/fonts/SFPro/SFPro-Regular.OTF
        - asset: assets/fonts/SFPro/SFPro-Italic.OTF
          style: italic
        - asset: assets/fonts/SFPro/SFPro-Bold.OTF
          weight: 700
